### ISSUE TITLE
Triangles can be used to *approximate* any shape in euclidean space

### ISSUE THREAD

**Issue by JulianDicken** [PaperPrototype/Intro-VoxelSystems-in-Unity#2]
> This is because triangles can be used to make any other shape.
Triangles can not be used to make e.g a circle in euclidean space. They can approximate circles or any non-polygonal shape but can never make up that shape. (I figure this should be added as a side note, it isnt that important but still factually incorrect otherwise)

**Comment by PaperPrototype** [comment]
Yup, thanks!

**Comment by PaperPrototype** [comment]
@DerJulien fixed it with the newest push.
